#
#Default values for amf

image:
  registry: docker.io
  repository: flavioandrade/amf
  tag: "latest"
  pullPolicy: IfNotPresent

services:
  ngap:
    type: LoadBalancer
    loadBalancerIP: 172.31.0.40
    provider: MetalLB

config: {}

global:
  containerPorts:
    sbi: 80
  mobileNetwork:
    name: Lance
    plmn:
      mcc: "001"
      mnc: "01"
      tac: 1
      s_nssai:
        - sst: 1
          sd: "000001"
