apiVersion: v2
appVersion: v2.7.5
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Open5GS UPF Helm chart
icon: https://open5gs.org/assets/img/open5gs-logo.png
name: upf
type: application
version: 0.3.3
