# Default values for nssf

image:
  registry: docker.io
  repository: flavioandrade/nssf
  tag: "latest"
  pullPolicy: IfNotPresent

config: {}

global:
  containerPorts:
    sbi: 80
  mobileNetwork:
    plmn:
      s_nssai:
        - sst: 1
          sd: "000001"
