# Default values for open5gs
global:
  networkFunctions:
    upf: []
  containerPorts:
    db: 27017
    sbi: 80
    webui: 9999
  mobileNetwork:
    name: NexusAI
    plmn:
      mcc: "001"
      mnc: "01"
      tac: 1
      s_nssai:
        - sst: 1
          sd: "000001"
    dataNetwork:
      subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: nexusAI

db:
  enabled: true
  image:
    registry: docker.io
    repository: mongo
    tag: "4.4"          # << versão compatível sem AVX
    pullPolicy: IfNotPresent
  services:
    db:
      type: NodePort
      nodePort: 30007
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
        
webui:
  enabled: true
  services:
    webui:
      type: LoadBalancer
      loadBalancerIP: 172.31.0.132
      #provider: MetalLB


nrf:
  enabled: true

ausf:
  enabled: true

bsf:
  enabled: true

nssf:
  enabled: true

pcf:
  enabled: true

udm:
  enabled: true

udr:
  enabled: true

amf:
  enabled: true
  services:
    ngap:
      type: LoadBalancer
      loadBalancerIP: 172.31.0.130
      provider: MetalLB

smf:
  enabled: true

upf:
  enabled: true
  services:
    gtpu:
      type: LoadBalancer
      loadBalancerIP: 172.31.0.131
      provider: MetalLB
