apiVersion: v2
appVersion: "8.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Open5GS DB Helm chart
name: db
type: application
version: 0.3.3
